version: "3.9"

services:
  wine-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wine_quality_app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    restart: unless-stopped
